server:
  port: 8081

spring:
  application:
    name: scrapper
  liquibase:
    change-log: classpath:scrapper-migrations/master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/linktracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: true
      file: "classpath:scrapper-infra/compose.yaml"

app:
  data:
    access-type: "ORM" # IN_MEM ORM SQL
  telegram:
    link:
      tracker:
        api-path: http://127.0.0.1:8080
        paths:
          updates: /updates
  snowflake:
    worker-id: 1
    datacenter-id: 1
  global:
    parallel-scrappers-amount: 5
  stackoverflow:
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    token: ${GITHUB_TOKEN}
    user-agent: github-events-scrapping-service

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg %kvp%n"
