# TODO may be move compose just to parent dir? (and have one for all services)
services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linktracker_scrapper
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - postgresql
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/changesets
    networks:
      - backend

volumes:
  pgdata:
