server:
  port: 8080

spring:
  application:
    name: bot

app:
  scrapper:
    api-path: http://127.0.0.1:8081
    paths:
      addChat: /tg-chat/{id}
      deleteChat: /tg-chat/{id}
      listLinks: /links
      trackLink: /links
      untrackLink: /links
  telegram:
    link:
      tracker:
        url: https://api.telegram.org/bot
        token: ${TELEGRAM_TOKEN} # Must be set in env
        init-state-try-set-fixed-rate: 1s
        max-messages-batch-size: 100
        update-listener-sleep: 1s
        debug: false
        update-notifier-before-retry: 10s
        processing-message-timeout: 10s
