package backend.academy.linktracker.scrapper.adapters.controllers.github.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.annotation.Generated;
import jakarta.validation.constraints.*;
import java.util.*;

@JsonIgnoreProperties(
        value = "status", // ignore manually set status, it will be automatically generated by Jackson during
        // serialization
        allowSetters = true // allows the status to be set during deserialization
        )
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "status", visible = true)
@JsonSubTypes({
    @JsonSubTypes.Type(value = ChecksCreateRequestOneOf.class, name = "checks_create_request_oneOf"),
    @JsonSubTypes.Type(value = ChecksCreateRequestOneOf1.class, name = "checks_create_request_oneOf_1")
})
@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2026-03-23T19:30:01.508827706Z[Etc/UTC]",
        comments = "Generator version: 7.21.0-SNAPSHOT")
public interface ChecksCreateRequest {
    public String getStatus();
}
