package backend.academy.linktracker.scrapper.adapters.controllers.github.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.annotation.Generated;
import java.util.Optional;

@JsonIgnoreProperties(
        value = "user_view_type", // ignore manually set user_view_type, it will be automatically generated by Jackson
        // during serialization
        allowSetters = true // allows the user_view_type to be set during deserialization
        )
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "user_view_type",
        visible = true)
@JsonSubTypes({
    @JsonSubTypes.Type(value = PrivateUser.class, name = "private"),
    @JsonSubTypes.Type(value = PublicUser.class, name = "public")
})
@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2026-04-05T13:06:55.012025427Z[Etc/UTC]",
        comments = "Generator version: 7.21.0-SNAPSHOT")
public interface UsersGetAuthenticated200Response {
    public Optional<String> getUserViewType();
}
